### ISSUE TITLE
Replacement of tag 0.1.0

### ISSUE THREAD

**Issue by y2sarakawa** [MarcusCalidus/marcuscalidus-svg-panel#12]
Tag 0.1.0 of this repository points to 2447f528a168e6ae4e00eeecb031732a0e133865.
I guess that should point to f6dd083c0c6a241f6a6b82f4f01cbf702ddeaf72.
Would you like to change the tag reference before registering in Grafana's repository?

**Comment by MarcusCalidus** [comment]
You're absolutely right. I removed 0.1.0 from the Grafana repository since it was not yet published. There's no use in publishing deprecated stuff. 
Added the 0.1.1 tag with the correct commit
