### ISSUE TITLE
No Demos offered?

### ISSUE THREAD

**Issue by jfisherith** [MarcusCalidus/marcuscalidus-svg-panel#13]
I cloned the repo into plugins.
ran npm and grunt and it builds
restart grafana and reload webpage
SVG builder seems to work.
Maybe I am missing it, but I see no demo options.
Can you help?

**Comment by MarcusCalidus** [comment]
Hi John,

the Demos are at the bottom of the SVG tab

![image](https://user-images.githubusercontent.com/4113366/42012534-0aa13508-7a99-11e8-9fab-867633e1ca27.png)

**Comment by jfisherith** [comment]
Thanks Marcus,

it was off the bottom of my screen, as you probably guessed, silly mistake.

I need to get more contrast in that scroll bar!


John Fisher
Sr Build Engineer
7402 Hollister Avenue | Santa Barbara CA 93117
805.562.8686 x221
________________________________
