### ISSUE TITLE
Multiple metrics exmple

### ISSUE THREAD

**Issue by marcin-kasinski** [MarcusCalidus/marcuscalidus-svg-panel#19]
Hello.

Your panel is great.

I'm trying to use it with my metrics.

I have simple problem.

My svg:

<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
 
 <g>
  <title>background</title>
  <rect fill="#fff" id="canvas_background" height="402" width="582" y="-1" x="-1"/>
  <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid">
   <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%"/>
  </g>
 </g>
 <g>
  <title>Layer 1</title>
  <text xml:space="preserve" id="metricA" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="12" y="20" x="10" stroke-width="0" stroke="#000" fill="#000000">X</text>
  <text xml:space="preserve" id="metricB" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="12" y="40" x="10" stroke-width="0" stroke="#000" fill="#000000">Y</text>
  <text xml:space="preserve" id="metricC" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="12" y="60" x="10" stroke-width="0" stroke="#000" fill="#000000">Z</text>
 </g>
</svg>

I've defined three metrics (metricA, metricB, metricB )

My question is:

Can you show me code which change may svg text values ( id="metricA" ,  id="metricB",  id="metricC") based on my metrics ?

I just don't get it.

**Comment by marcin-kasinski** [comment]
I've solved it.
Sorry....

**Comment by MarcusCalidus** [comment]
That was fast. Good job and thank you for your compliment.
