### ISSUE TITLE
Table format data is not supported

### ISSUE THREAD

**Issue by saurla** [MarcusCalidus/marcuscalidus-svg-panel#25]
It is not possible to get data from data source in table format. Only time series is supported. 

![image](https://user-images.githubusercontent.com/24889872/47968154-662c3e00-e06e-11e8-9981-3cb561686f74.png)

**Comment by MarcusCalidus** [comment]
fixed with https://github.com/MarcusCalidus/marcuscalidus-svg-panel/pull/26
Thank you for the suggestion and fix.
