### ISSUE TITLE
Need help to create the polar chart and showing data to the graph

### ISSUE THREAD

**Issue by pamani** [MarcusCalidus/marcuscalidus-svg-panel#33]
I am trying to create polar chart using this plugin.
Could you please provide some document or help guide so I can use this plugin?

**Comment by MarcusCalidus** [comment]
the first thing you need is the basic polar chart as svg. The lines into the chart can be drawn via snap.svg.
A simple example what can be done and how to do it can be found here: https://codepen.io/ggaulard/pen/BfkIx

The only thing that is plugin specific is using the actual values from the Grafana datasource.

does this help a little?
