### ISSUE TITLE
Scaling of graphics

### ISSUE THREAD

**Issue by deothermo** [MarcusCalidus/marcuscalidus-svg-panel#5]
Hi Marcus,

thanks for your excellent contribution. 

Do you know if there is an easy way to enable scaling of the svg panels? On my desktop, the panel looks fine. However, on my mobile the graph is not scaled but shown with its original size which does not fit on the screen.

Best,

Dennis

**Comment by MarcusCalidus** [comment]
Hi Dennis,

I suppose there is an issue with your svg. Ours scale well this is the outer svg element of one of the graphics we use:

```
<svg id="svg2" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="100%" width="100%" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 362.14257 152.15235">

</svg>
```

Please make sure to use width and height attribute as well as a viewBox.

Best regards
Marco

**Comment by deothermo** [comment]
Marco,

thanks. Seems to be an issue with my svg definitions indeed. 

I am currently using inkscape to create the svg, however it includes a lot of "bloat". Do you have any other recommendation for a good svg editor, which creates nice & clean definitions?

Regards,

Dennis

**Comment by MarcusCalidus** [comment]
Hey Dennis,

you might want to try https://jakearchibald.github.io/svgomg/ 
This tool is especially designed to streamline SVG. This already helped with other issues (https://github.com/MarcusCalidus/marcuscalidus-svg-panel/issues/3)

Hope this will help you
best wishes
Marco

**Comment by deothermo** [comment]
Excellent, this did the trick.
