### ISSUE TITLE
SVG does not appear

### ISSUE THREAD

**Issue by rajil** [MarcusCalidus/marcuscalidus-svg-panel#6]
I am trying to setup the plugin in grafana-5.0.4 running on Centos 7. I cloned the git repo at /var/lib/grafana/plugins. The SVG plugin appears in the list of plugins.

When I add a SVG panel and try to use SVG builder i get an empty page.

![image](https://user-images.githubusercontent.com/379266/38433209-a41ade8c-398f-11e8-80ea-80e9d0d484df.png)

Any idea what am i missing and where do i find the demo pages?

**Comment by MarcusCalidus** [comment]
Hi Rajil,

after selecting a svg from the repo you have to press the `+ Add` button to add the selected graphic to the elements list. Like so:
![image](https://user-images.githubusercontent.com/4113366/38452796-8f977e22-3a4b-11e8-8453-73b3346d0032.png)

The demos can be access via the SVG tab:
![image](https://user-images.githubusercontent.com/4113366/38452788-64dc739a-3a4b-11e8-8d1b-b9337d8a432a.png)

**Comment by rajil** [comment]
Thanks. This works as you have demonstrated.
