### ISSUE TITLE
Custom repository isnt picked

### ISSUE THREAD

**Issue by rajil** [MarcusCalidus/marcuscalidus-svg-panel#7]
I have added an additonal repository 'testrepo'  in repositories.json. Unfortunately, the 'testrepo' still does not appear in the drop down menu. Any idea why?

```
{
    "rtmaster" : {
        "url": "https://github.com/rtmaster",
        "description": "simple examples",
        "license": "Apache 2.0",
        "items" : [
                {
                    "category": "arrows",
                    "name": "arrow-up",
                    "path": "rtmaster/arrows/arrow-up.svg",
                    "description": "Arrow facing up"
                }
            ]
    }
    "testrepo" : {
        "description": "Test repo",
        "license": "Apache 2.0",
        "items" : [
                {
                    "category": "testcategory",
                    "name": "testfile",
                    "path": "testrepo/arrows/testfile.svg",
                    "description": "test file"
                }
            ]
}
```

```
# tree testrepo
testrepo
└── testcategory
    └── testfile.svg

1 directory, 1 file

```

**Comment by MarcusCalidus** [comment]
Hi Rajil,

thank you for your question. Which repository file are you editing? I recommend to copy your `testrepo` folder to the `assets` folder, edit the `assets/repositories.json` and run `npm run build` afterwards. 

That said, there is a problem with your json. You are missing a comma and a closing curly bracket. This one works:

```
{
    "rtmaster": {
        "url": "https://github.com/rtmaster",
        "description": "simple examples",
        "license": "Apache 2.0",
        "items": [{
            "category": "arrows",
            "name": "arrow-up",
            "path": "rtmaster/arrows/arrow-up.svg",
            "description": "Arrow facing up"
        }]
    },
    "testrepo": {
        "description": "Test repo",
        "license": "Apache 2.0",
        "items": [{
            "category": "testcategory",
            "name": "testfile",
            "path": "testrepo/arrows/testfile.svg",
            "description": "test file"
        }]
    }
}
```

**Comment by rajil** [comment]
Thanks I fixed the repo file followed by npm build, and restarted grafana. Unfortunately, I dont see the 'testrepo' in the drop-down menu. 

My setup is as follows:I have cloned the plugin at /home/grafana/grafanaplugins/marcuscalidus-svg-panel. Installed using the following,
```
[root@localhost marcuscalidus-svg-panel]#npm install
└─┬ snapsvg@0.5.1 
  └── eve@0.5.4 
npm WARN grunt-execute@0.2.2 requires a peer of grunt@~0.4.1 but none was installed.

[root@localhost marcuscalidus-svg-panel]# npm build
[root@localhost marcuscalidus-svg-panel]# grunt
Running "clean:0" (clean) task
>> 1 path cleaned.

Running "copy:src_to_dist" (copy) task
Copied 5 files

Running "copy:img_to_dist" (copy) task
Created 1 directory, copied 8 files

Running "copy:assets_to_dist" (copy) task
Created 14 directories, copied 116 files

Running "copy:pluginDef" (copy) task
Copied 2 files

Running "babel:dist" (babel) task

Running "copy:frameworks" (copy) task
Copied 8 files

Done.

``` 
The fixed repo file is at https://pastebin.com/pgh1Vgug

Any idea what could be the issue?

**Comment by MarcusCalidus** [comment]
Hi Rajil,

I guess your browser is playing tricks on you. It might have cached the json file.
I tried out your repository.json and it works. These are the steps:

1. edit the json repo
2. run `npm run build `
3. restart grafana service
4. in browser hard reload the grafana website 
     depending on your system like so: 
![image](https://user-images.githubusercontent.com/4113366/38484794-02fcce16-3bd8-11e8-91c2-f9811a7d8c08.png)

Hope this'll help

**Comment by rajil** [comment]
Thanks, your instructions worked.
