### ISSUE TITLE
dashboard variables

### ISSUE THREAD

**Issue by yosiasz** [MarcusCalidus/marcuscalidus-svg-panel#71]
Greetings

How does one capture values from dashboard variables?

**Comment by MarcusCalidus** [comment]
Hi Yosais,

I guess you could try looking at this array. I am not sure if you'll find the necessary information there:

`ctrl.templateSrv.variables`

I guess you should just log it to console and see if anything useful is in there. 

Hope this helps. Cheers,
Marco

**Comment by yosiasz** [comment]
Thanks very much it does indeed help!
