### ISSUE TITLE
Official Grafana plugin

### ISSUE THREAD

**Issue by kjetilmjos** [MarcusCalidus/marcuscalidus-svg-panel#9]
Hi @MarcusCalidus like your plugin :) Would be really nice if it was included in the official Grafana plugin list https://grafana.com/plugins

**Comment by MarcusCalidus** [comment]
Hi @kjetilmjos , 
thank you for your commendation. There is actually already a pull request regarding that matter:
https://github.com/grafana/grafana-plugin-repository/pull/229
There is nothing more from my side that I can do about it. We'll have to wait for @daniellee from Grafana Labs. 
I guess it would be great to stay tuned ;-)

cheers 
Marco
